# Generated by Django 5.2.4 on 2026-01-03 09:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('image', models.CharField(default='box.png', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='Skin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image_name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('is_free', models.BooleanField(default=False)),
                ('price', models.IntegerField(default=0)),
                ('unlock_requirement', models.CharField(blank=True, max_length=200, null=True)),
                ('required_clicks', models.IntegerField(default=0)),
                ('required_coins', models.IntegerField(default=0)),
                ('rarity', models.CharField(default='common', max_length=20)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Upgrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('upgrade_type', models.CharField(choices=[('click_power', 'Усиление клика'), ('auto_clicker', 'Автокликер'), ('critical_chance', 'Шанс крита'), ('coin_multiplier', 'Множитель монет')], default='click_power', max_length=20)),
                ('base_cost', models.IntegerField(default=10)),
                ('current_cost', models.IntegerField(default=10)),
                ('level', models.IntegerField(default=1)),
                ('cost_multiplier', models.FloatField(default=1.5)),
                ('max_level', models.IntegerField(default=20)),
                ('click_power_increase', models.IntegerField(default=0)),
                ('auto_clicker_speed', models.IntegerField(default=0)),
                ('critical_chance', models.FloatField(default=0)),
                ('coin_multiplier', models.FloatField(default=1.0)),
            ],
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('achievement_type', models.CharField(choices=[('clicks', 'Клики'), ('coins', 'Монеты'), ('upgrades', 'Улучшения'), ('special', 'Специальные'), ('collection', 'Коллекция')], max_length=20)),
                ('icon', models.CharField(default='fas fa-trophy', max_length=100)),
                ('required_clicks', models.BigIntegerField(default=0)),
                ('required_coins', models.BigIntegerField(default=0)),
                ('required_upgrades', models.IntegerField(default=0)),
                ('required_wins', models.IntegerField(default=0)),
                ('required_collection', models.JSONField(blank=True, default=dict, null=True)),
                ('reward_coins', models.BigIntegerField(default=0)),
                ('reward_click_power', models.IntegerField(default=0)),
                ('reward_auto_clicker', models.IntegerField(default=0)),
                ('reward_critical_chance', models.FloatField(default=0)),
                ('reward_coin_multiplier', models.FloatField(default=0)),
                ('unlock_skin', models.CharField(blank=True, max_length=100, null=True)),
                ('badge_color', models.CharField(default='#FFD700', max_length=20)),
                ('rarity', models.CharField(choices=[('common', 'Обычное'), ('uncommon', 'Необычное'), ('rare', 'Редкое'), ('epic', 'Эпическое'), ('legendary', 'Легендарное')], default='common', max_length=20)),
                ('order', models.IntegerField(default=0)),
                ('is_secret', models.BooleanField(default=False)),
                ('secret_description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'rarity', 'name'],
                'indexes': [models.Index(fields=['achievement_type'], name='main_achiev_achieve_43d5d9_idx'), models.Index(fields=['rarity'], name='main_achiev_rarity_957815_idx')],
            },
        ),
        migrations.CreateModel(
            name='Battle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('waiting', 'Ожидание соперника'), ('active', 'В процессе'), ('finished', 'Завершен')], default='waiting', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(null=True)),
                ('finished_at', models.DateTimeField(null=True)),
                ('duration', models.IntegerField(default=60)),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battles_as_player1', to=settings.AUTH_USER_MODEL)),
                ('player2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='battles_as_player2', to=settings.AUTH_USER_MODEL)),
                ('winner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_battles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BattleInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('accepted', 'Принято'), ('rejected', 'Отклонено')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('battle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.battle')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invites', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_invites', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BattleParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clicks', models.IntegerField(default=0)),
                ('score', models.IntegerField(default=0)),
                ('is_ready', models.BooleanField(default=False)),
                ('battle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='main.battle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BoxDrop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('skin', 'Скин'), ('coins', 'Монеты'), ('clicks', 'Клики')], max_length=10)),
                ('item_value', models.CharField(max_length=100)),
                ('drop_chance', models.FloatField()),
                ('is_rare', models.BooleanField(default=False)),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drops', to='main.box')),
            ],
            options={
                'ordering': ['-is_rare', '-drop_chance'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clicks', models.IntegerField(default=0)),
                ('coins', models.IntegerField(default=0)),
                ('click_power', models.IntegerField(default=1)),
                ('auto_clicker_power', models.IntegerField(default=0)),
                ('critical_chance', models.FloatField(default=0.0)),
                ('coin_multiplier', models.FloatField(default=1.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('current_skin', models.CharField(default='cat.png', max_length=100)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BoxOpening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(max_length=10)),
                ('item_value', models.CharField(max_length=100)),
                ('is_rare', models.BooleanField(default=False)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.box')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='box_openings', to='main.player')),
            ],
            options={
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='PlayerAutoClicker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clicks_per_second', models.IntegerField(default=0)),
                ('last_auto_click', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auto_clicker', to='main.player')),
            ],
        ),
        migrations.CreateModel(
            name='ResourceTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(choices=[('clicks', 'Клики'), ('coins', 'Монеты'), ('upgrades', 'Улучшения'), ('skins', 'Скины')], max_length=20)),
                ('resource_amount', models.CharField(max_length=100)),
                ('want_type', models.CharField(choices=[('clicks', 'Клики'), ('coins', 'Монеты'), ('upgrades', 'Улучшения'), ('skins', 'Скины')], max_length=20)),
                ('want_amount', models.CharField(max_length=100)),
                ('status', models.CharField(default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers_made', to='main.player')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlayerAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('progress_data', models.JSONField(default=dict)),
                ('is_new', models.BooleanField(default=True)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.achievement')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='main.player')),
            ],
            options={
                'ordering': ['-unlocked_at'],
                'unique_together': {('player', 'achievement')},
            },
        ),
        migrations.CreateModel(
            name='PlayerSkin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('is_selected', models.BooleanField(default=False)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlocked_skins', to='main.player')),
                ('skin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.skin')),
            ],
            options={
                'unique_together': {('player', 'skin')},
            },
        ),
        migrations.CreateModel(
            name='PlayerUpgrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_upgrades', to='main.player')),
                ('upgrade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_upgrades', to='main.upgrade')),
            ],
            options={
                'unique_together': {('player', 'upgrade')},
            },
        ),
    ]
