# Generated by Django 5.2.4 on 2026-01-03 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='image',
            field=models.CharField(default='box.svg', max_length=100),
        ),
    ]
