# Generated by Django 5.2.4 on 2026-01-13 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_box_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='required_collection',
            field=models.TextField(blank=True, default='{}', null=True),
        ),
        migrations.AlterField(
            model_name='playerachievement',
            name='progress_data',
            field=models.TextField(default='{}'),
        ),
    ]
